window.QUESTION_BANK = [
  {
    topic: "Java",
    level: "easy",
    type: "choice",
    question: "Which keyword is used to create a class in Java?",
    options: ["class", "object", "struct", "define"],
    answer: "class",
    explanation: "`class` declares a Java class. Objects are created from classes."
  },
  {
    topic: "Java",
    level: "easy",
    type: "choice",
    question: "Which Java type is commonly used for true or false values?",
    options: ["int", "boolean", "String", "double"],
    answer: "boolean",
    explanation: "`boolean` stores either `true` or `false`."
  },
  {
    topic: "Java",
    level: "easy",
    type: "trueFalse",
    question: "Java source files usually use the `.java` extension.",
    answer: "True",
    explanation: "Java source code is written in `.java` files and compiled into bytecode."
  },
  {
    topic: "Java",
    level: "easy",
    type: "short",
    question: "What method name is the usual entry point of a Java application?",
    answer: "main",
    explanation: "The JVM starts a normal Java program from the `main` method."
  },
  {
    topic: "Java",
    level: "medium",
    type: "choice",
    question: "Which statement about Java interfaces is correct?",
    options: [
      "A class can implement multiple interfaces",
      "Interfaces must be instantiated directly",
      "Interfaces cannot contain constants",
      "A class can extend multiple classes"
    ],
    answer: "A class can implement multiple interfaces",
    explanation: "Java allows a class to implement multiple interfaces, while class inheritance is single inheritance."
  },
  {
    topic: "Java",
    level: "medium",
    type: "choice",
    question: "Which collection does not allow duplicate elements?",
    options: ["List", "Set", "Queue", "Map"],
    answer: "Set",
    explanation: "`Set` represents unique elements. `Map` stores key-value pairs, not plain elements."
  },
  {
    topic: "Java",
    level: "medium",
    type: "trueFalse",
    question: "`HashMap` guarantees insertion order.",
    answer: "False",
    explanation: "`HashMap` does not guarantee iteration order. `LinkedHashMap` preserves insertion order."
  },
  {
    topic: "Java",
    level: "medium",
    type: "short",
    question: "What Java feature lets one method name have different parameter lists?",
    answer: "overloading",
    explanation: "Method overloading means same method name, different parameters."
  },
  {
    topic: "Java",
    level: "hard",
    type: "choice",
    question: "Which statement about `equals` and `hashCode` is correct?",
    options: [
      "Equal objects should return the same hash code",
      "Equal objects must be the same instance",
      "`hashCode` decides object equality by itself",
      "`equals` must always compare every field"
    ],
    answer: "Equal objects should return the same hash code",
    explanation: "The contract requires equal objects to have the same hash code, especially for hash-based collections."
  },
  {
    topic: "Java",
    level: "hard",
    type: "trueFalse",
    question: "A checked exception must be caught or declared by the method signature.",
    answer: "True",
    explanation: "Checked exceptions are enforced by the compiler unless handled or declared with `throws`."
  },
  {
    topic: "Java",
    level: "hard",
    type: "short",
    question: "Which keyword marks a variable as not serialized by Java serialization?",
    answer: "transient",
    explanation: "`transient` tells Java serialization to skip that field."
  },
  {
    topic: "SQL",
    level: "easy",
    type: "choice",
    question: "Which SQL command is used to read rows from a table?",
    options: ["SELECT", "INSERT", "UPDATE", "DELETE"],
    answer: "SELECT",
    explanation: "`SELECT` retrieves data from one or more tables."
  },
  {
    topic: "SQL",
    level: "easy",
    type: "trueFalse",
    question: "`WHERE` is used to filter rows in a query.",
    answer: "True",
    explanation: "`WHERE` limits rows to those matching a condition."
  },
  {
    topic: "SQL",
    level: "easy",
    type: "short",
    question: "Which clause sorts SQL query results?",
    answer: "ORDER BY",
    explanation: "`ORDER BY` sorts rows by one or more columns."
  },
  {
    topic: "SQL",
    level: "medium",
    type: "choice",
    question: "Which join returns rows that have matching values in both tables?",
    options: ["INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN", "CROSS JOIN"],
    answer: "INNER JOIN",
    explanation: "`INNER JOIN` keeps only matching rows from both sides."
  },
  {
    topic: "SQL",
    level: "medium",
    type: "trueFalse",
    question: "`GROUP BY` is commonly used together with aggregate functions.",
    answer: "True",
    explanation: "`GROUP BY` groups rows so functions like `COUNT`, `SUM`, and `AVG` can summarize them."
  },
  {
    topic: "SQL",
    level: "medium",
    type: "short",
    question: "Which SQL keyword removes duplicate rows from query results?",
    answer: "DISTINCT",
    explanation: "`DISTINCT` returns unique result rows."
  },
  {
    topic: "SQL",
    level: "hard",
    type: "choice",
    question: "Which clause filters grouped results after aggregation?",
    options: ["HAVING", "WHERE", "ORDER BY", "LIMIT"],
    answer: "HAVING",
    explanation: "`WHERE` filters rows before grouping; `HAVING` filters groups after aggregation."
  },
  {
    topic: "SQL",
    level: "hard",
    type: "trueFalse",
    question: "A database transaction should satisfy ACID properties.",
    answer: "True",
    explanation: "ACID stands for Atomicity, Consistency, Isolation, and Durability."
  },
  {
    topic: "SQL",
    level: "hard",
    type: "short",
    question: "What isolation problem happens when one transaction reads uncommitted changes from another?",
    answer: "dirty read",
    explanation: "A dirty read means reading data that may still be rolled back."
  },
  {
    topic: "PostgreSQL",
    level: "easy",
    type: "choice",
    question: "Which PostgreSQL command lists databases in the `psql` shell?",
    options: ["\\l", "\\d", "\\c", "\\q"],
    answer: "\\l",
    explanation: "In `psql`, `\\l` lists available databases."
  },
  {
    topic: "PostgreSQL",
    level: "easy",
    type: "trueFalse",
    question: "PostgreSQL is a relational database.",
    answer: "True",
    explanation: "PostgreSQL is an open-source relational database system."
  },
  {
    topic: "PostgreSQL",
    level: "easy",
    type: "short",
    question: "Which PostgreSQL type is often used for auto-incrementing integer IDs?",
    answer: "serial",
    explanation: "`serial` is a common shorthand for auto-incrementing integer IDs."
  },
  {
    topic: "PostgreSQL",
    level: "medium",
    type: "choice",
    question: "Which PostgreSQL feature stores semi-structured JSON data efficiently?",
    options: ["JSONB", "VARCHAR", "SERIAL", "BOOLEAN"],
    answer: "JSONB",
    explanation: "`JSONB` stores JSON in a binary format and supports indexing."
  },
  {
    topic: "PostgreSQL",
    level: "medium",
    type: "trueFalse",
    question: "An index can speed up reads but may add cost to writes.",
    answer: "True",
    explanation: "Indexes must be maintained during inserts, updates, and deletes."
  },
  {
    topic: "PostgreSQL",
    level: "medium",
    type: "short",
    question: "Which command shows the execution plan of a PostgreSQL query?",
    answer: "EXPLAIN",
    explanation: "`EXPLAIN` shows how PostgreSQL plans to execute a query."
  },
  {
    topic: "PostgreSQL",
    level: "hard",
    type: "choice",
    question: "Which index type is commonly used for full-text search in PostgreSQL?",
    options: ["GIN", "BTREE", "HASH", "BRIN"],
    answer: "GIN",
    explanation: "GIN indexes are commonly used for full-text search and JSONB queries."
  },
  {
    topic: "PostgreSQL",
    level: "hard",
    type: "trueFalse",
    question: "`VACUUM` helps PostgreSQL reclaim storage from dead rows.",
    answer: "True",
    explanation: "PostgreSQL uses MVCC, so vacuuming cleans up old row versions."
  },
  {
    topic: "PostgreSQL",
    level: "hard",
    type: "short",
    question: "What PostgreSQL mechanism allows multiple versions of rows for transaction isolation?",
    answer: "MVCC",
    explanation: "MVCC means Multi-Version Concurrency Control."
  },
  {
    topic: "Spring Boot",
    level: "easy",
    type: "choice",
    question: "Which annotation marks a class as a REST controller in Spring?",
    options: ["@RestController", "@Entity", "@Autowired", "@Bean"],
    answer: "@RestController",
    explanation: "`@RestController` combines controller behavior with automatic response body serialization."
  },
  {
    topic: "Spring Boot",
    level: "easy",
    type: "trueFalse",
    question: "Spring Boot can start an embedded web server.",
    answer: "True",
    explanation: "Spring Boot apps commonly run with embedded Tomcat, Jetty, or Undertow."
  },
  {
    topic: "Spring Boot",
    level: "easy",
    type: "short",
    question: "Which file commonly stores Spring Boot configuration properties?",
    answer: "application.properties",
    explanation: "`application.properties` or `application.yml` commonly stores app settings."
  },
  {
    topic: "Spring Boot",
    level: "medium",
    type: "choice",
    question: "Which annotation maps HTTP GET requests to a handler method?",
    options: ["@GetMapping", "@PostMapping", "@Service", "@Repository"],
    answer: "@GetMapping",
    explanation: "`@GetMapping` is a shortcut for mapping GET requests."
  },
  {
    topic: "Spring Boot",
    level: "medium",
    type: "trueFalse",
    question: "`@Service` is usually used for business logic classes.",
    answer: "True",
    explanation: "`@Service` marks service-layer components and lets Spring detect them."
  },
  {
    topic: "Spring Boot",
    level: "medium",
    type: "short",
    question: "What pattern does Spring use to provide objects to classes instead of creating them manually?",
    answer: "dependency injection",
    explanation: "Dependency injection lets Spring wire objects and reduce manual construction."
  },
  {
    topic: "Spring Boot",
    level: "hard",
    type: "choice",
    question: "Which Spring Boot feature exposes health, metrics, and operational endpoints?",
    options: ["Actuator", "JPA", "Lombok", "Flyway"],
    answer: "Actuator",
    explanation: "Spring Boot Actuator provides production-ready monitoring and management endpoints."
  },
  {
    topic: "Spring Boot",
    level: "hard",
    type: "trueFalse",
    question: "`@Transactional` can roll back a transaction when an unchecked exception occurs.",
    answer: "True",
    explanation: "By default, Spring rolls back transactions for runtime exceptions."
  },
  {
    topic: "Spring Boot",
    level: "hard",
    type: "short",
    question: "Which Spring interface can run logic after the application context starts?",
    answer: "CommandLineRunner",
    explanation: "`CommandLineRunner` executes code after the Spring application has started."
  },
  {
    topic: "Kafka",
    level: "easy",
    type: "choice",
    question: "What is a Kafka topic?",
    options: ["A named stream of records", "A SQL table", "A Java class", "A REST endpoint"],
    answer: "A named stream of records",
    explanation: "Kafka stores records in named topics."
  },
  {
    topic: "Kafka",
    level: "easy",
    type: "trueFalse",
    question: "A Kafka producer sends messages to Kafka.",
    answer: "True",
    explanation: "Producers publish records to topics."
  },
  {
    topic: "Kafka",
    level: "easy",
    type: "short",
    question: "What is the component that reads records from Kafka called?",
    answer: "consumer",
    explanation: "Consumers subscribe to topics and read records."
  },
  {
    topic: "Kafka",
    level: "medium",
    type: "choice",
    question: "Why are Kafka topics split into partitions?",
    options: [
      "To scale throughput and parallel processing",
      "To remove the need for brokers",
      "To convert messages to SQL",
      "To make every message global ordered"
    ],
    answer: "To scale throughput and parallel processing",
    explanation: "Partitions allow Kafka to distribute load and let consumers process in parallel."
  },
  {
    topic: "Kafka",
    level: "medium",
    type: "trueFalse",
    question: "Kafka guarantees ordering within a single partition.",
    answer: "True",
    explanation: "Kafka preserves record order inside each partition, not across all partitions."
  },
  {
    topic: "Kafka",
    level: "medium",
    type: "short",
    question: "What Kafka value identifies a consumer's position in a partition?",
    answer: "offset",
    explanation: "An offset is the position of a record in a partition."
  },
  {
    topic: "Kafka",
    level: "hard",
    type: "choice",
    question: "What does a consumer group allow?",
    options: [
      "Multiple consumers to share partitions of subscribed topics",
      "One consumer to receive every partition duplicate",
      "A producer to write without a topic",
      "A broker to store relational tables"
    ],
    answer: "Multiple consumers to share partitions of subscribed topics",
    explanation: "Kafka assigns partitions among consumers in the same group for scalable consumption."
  },
  {
    topic: "Kafka",
    level: "hard",
    type: "trueFalse",
    question: "Kafka retention is based only on whether consumers have read the messages.",
    answer: "False",
    explanation: "Kafka retention is usually time- or size-based, independent of individual consumer reads."
  },
  {
    topic: "Kafka",
    level: "hard",
    type: "short",
    question: "What Kafka concept copies partition data across brokers for fault tolerance?",
    answer: "replication",
    explanation: "Replication keeps partition copies on multiple brokers."
  },
  {
    topic: "Git",
    level: "easy",
    type: "choice",
    question: "Which command records staged changes in Git history?",
    options: ["git commit", "git push", "git clone", "git status"],
    answer: "git commit",
    explanation: "`git commit` saves staged changes as a new commit."
  },
  {
    topic: "Git",
    level: "easy",
    type: "trueFalse",
    question: "`git status` shows changed files and staging state.",
    answer: "True",
    explanation: "`git status` summarizes the working tree and staging area."
  },
  {
    topic: "Git",
    level: "easy",
    type: "short",
    question: "Which command downloads a repository for the first time?",
    answer: "git clone",
    explanation: "`git clone` copies an existing repository locally."
  },
  {
    topic: "Git",
    level: "medium",
    type: "choice",
    question: "What does `git pull` usually do?",
    options: [
      "Fetches remote changes and integrates them",
      "Deletes local commits",
      "Creates a new repository",
      "Shows only staged files"
    ],
    answer: "Fetches remote changes and integrates them",
    explanation: "`git pull` fetches from a remote and then merges or rebases depending on configuration."
  },
  {
    topic: "Git",
    level: "medium",
    type: "trueFalse",
    question: "A branch is a movable pointer to a commit.",
    answer: "True",
    explanation: "Branches move as new commits are added."
  },
  {
    topic: "Git",
    level: "medium",
    type: "short",
    question: "Which Git command temporarily stores uncommitted changes?",
    answer: "git stash",
    explanation: "`git stash` saves local changes so the working tree can be cleaned temporarily."
  },
  {
    topic: "Git",
    level: "hard",
    type: "choice",
    question: "What is a rebase commonly used for?",
    options: [
      "Reapplying commits on top of another base commit",
      "Deleting the remote repository",
      "Showing disk usage",
      "Encrypting commits"
    ],
    answer: "Reapplying commits on top of another base commit",
    explanation: "Rebase rewrites commit ancestry by replaying commits onto a new base."
  },
  {
    topic: "Git",
    level: "hard",
    type: "trueFalse",
    question: "Changing published shared history with force push can disrupt teammates.",
    answer: "True",
    explanation: "Force pushing rewritten history may break other people's local branches."
  },
  {
    topic: "Git",
    level: "hard",
    type: "short",
    question: "Which Git command finds the commit that introduced a bug using binary search?",
    answer: "git bisect",
    explanation: "`git bisect` searches history to identify the first bad commit."
  },
  {topic:"Java",level:"easy",type:"choice",question:"Which keyword creates an object in Java?",options:["new","make","create","instance"],answer:"new",explanation:"The `new` keyword allocates an object and invokes a constructor."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"Java variable names are case-sensitive.",answer:"True",explanation:"`count` and `Count` are different identifiers in Java."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword declares a constant variable in Java?",answer:"final",explanation:"A `final` variable can be assigned only once."},
  {topic:"Java",level:"medium",type:"choice",question:"Which interface is the root of the Java collection hierarchy?",options:["Collection","Iterable","List","Iterator"],answer:"Collection",explanation:"`Collection` is the main root interface for groups of objects; `Map` is separate."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"An abstract class can be instantiated directly.",answer:"False",explanation:"Abstract classes must be extended before concrete subclasses can be instantiated."},
  {topic:"Java",level:"medium",type:"short",question:"Which Java keyword refers to the current object?",answer:"this",explanation:"`this` refers to the current object instance."},
  {topic:"Java",level:"hard",type:"choice",question:"Which garbage collector concept describes an object that can no longer be reached?",options:["Unreachable object","Pinned object","Escaped object","Root object"],answer:"Unreachable object",explanation:"An unreachable object may be reclaimed by the garbage collector."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"A Java `finally` block normally runs whether an exception is thrown or not.",answer:"True",explanation:"`finally` is intended for cleanup and normally executes after try/catch flow."},
  {topic:"SQL",level:"easy",type:"choice",question:"Which SQL command adds new rows to a table?",options:["INSERT","ADD","CREATE","APPEND"],answer:"INSERT",explanation:"`INSERT` adds one or more rows to a table."},
  {topic:"SQL",level:"easy",type:"trueFalse",question:"A primary key identifies each row uniquely.",answer:"True",explanation:"A primary key constraint prevents duplicate key values."},
  {topic:"SQL",level:"easy",type:"short",question:"Which SQL command changes existing rows?",answer:"UPDATE",explanation:"`UPDATE` changes values in rows that match its condition."},
  {topic:"SQL",level:"medium",type:"choice",question:"Which function counts rows in SQL?",options:["COUNT","TOTAL","ROWS","SIZE"],answer:"COUNT",explanation:"`COUNT` returns the number of rows or non-NULL values."},
  {topic:"SQL",level:"medium",type:"trueFalse",question:"A NULL value is the same as an empty string.",answer:"False",explanation:"NULL means unknown or missing; an empty string is a value."},
  {topic:"SQL",level:"medium",type:"short",question:"Which SQL command permanently removes a table definition?",answer:"DROP TABLE",explanation:"`DROP TABLE` removes the table and its definition."},
  {topic:"SQL",level:"hard",type:"choice",question:"What is database normalization mainly intended to reduce?",options:["Data redundancy","Network latency","Query syntax","User permissions"],answer:"Data redundancy",explanation:"Normalization reduces duplication and update anomalies."},
  {topic:"SQL",level:"hard",type:"trueFalse",question:"A composite index can contain more than one column.",answer:"True",explanation:"A composite index is built from multiple columns in a defined order."},
  {topic:"PostgreSQL",level:"easy",type:"choice",question:"Which PostgreSQL command connects to a database in `psql`?",options:["\\c","\\l","\\d","\\q"],answer:"\\c",explanation:"In `psql`, `\\c database_name` connects to another database."},
  {topic:"PostgreSQL",level:"easy",type:"trueFalse",question:"PostgreSQL supports transactions.",answer:"True",explanation:"PostgreSQL provides COMMIT and ROLLBACK transaction commands."},
  {topic:"PostgreSQL",level:"easy",type:"short",question:"Which PostgreSQL command exits the `psql` shell?",answer:"\\q",explanation:"The `\\q` meta-command quits the `psql` client."},
  {topic:"PostgreSQL",level:"medium",type:"choice",question:"Which PostgreSQL type stores a calendar date and time with a time zone?",options:["timestamp with time zone","date","time","interval"],answer:"timestamp with time zone",explanation:"This type stores an instant while displaying it in the session time zone."},
  {topic:"PostgreSQL",level:"medium",type:"trueFalse",question:"PostgreSQL can create indexes on expressions.",answer:"True",explanation:"Expression indexes can index a computed expression such as lower(email)."},
  {topic:"PostgreSQL",level:"medium",type:"short",question:"Which PostgreSQL command creates a new table?",answer:"CREATE TABLE",explanation:"`CREATE TABLE` defines a new table and its columns."},
  {topic:"PostgreSQL",level:"hard",type:"choice",question:"Which PostgreSQL isolation level prevents dirty reads but may allow phantom reads?",options:["Read Committed","Read Uncommitted","Serializable only","No Isolation"],answer:"Read Committed",explanation:"Read Committed is PostgreSQL's default isolation level."},
  {topic:"PostgreSQL",level:"hard",type:"trueFalse",question:"A PostgreSQL foreign key can reference a unique key, not only a primary key.",answer:"True",explanation:"Referenced columns may use a primary key or suitable unique constraint."},
  {topic:"Spring Boot",level:"easy",type:"choice",question:"Which annotation marks a class as a Spring-managed component?",options:["@Component","@Value","@Profile","@Import"],answer:"@Component",explanation:"`@Component` makes a class eligible for component scanning."},
  {topic:"Spring Boot",level:"easy",type:"trueFalse",question:"Spring Boot starters provide convenient dependency bundles.",answer:"True",explanation:"Starters group commonly used dependencies for a feature."},
  {topic:"Spring Boot",level:"easy",type:"short",question:"Which annotation injects a configuration value into a field?",answer:"@Value",explanation:"`@Value` can inject a property or expression into a Spring bean."},
  {topic:"Spring Boot",level:"medium",type:"choice",question:"Which annotation maps a Java class to a database table in JPA?",options:["@Entity","@TableOnly","@Record","@Documented"],answer:"@Entity",explanation:"`@Entity` marks a class as a persistent JPA entity."},
  {topic:"Spring Boot",level:"medium",type:"trueFalse",question:"Spring profiles can activate different configuration for different environments.",answer:"True",explanation:"Profiles allow environment-specific beans and properties."},
  {topic:"Spring Boot",level:"medium",type:"short",question:"Which annotation maps an HTTP POST request in Spring MVC?",answer:"@PostMapping",explanation:"`@PostMapping` maps handler methods to HTTP POST requests."},
  {topic:"Spring Boot",level:"hard",type:"choice",question:"Which Spring mechanism handles cross-cutting concerns such as transactions?",options:["AOP proxies","JDBC drivers","Servlet filters only","JPA entities"],answer:"AOP proxies",explanation:"Spring commonly applies cross-cutting behavior through proxies."},
  {topic:"Spring Boot",level:"hard",type:"trueFalse",question:"Constructor injection makes required dependencies explicit to a class.",answer:"True",explanation:"Constructor injection makes dependencies visible and supports immutable fields."},
  {topic:"Kafka",level:"easy",type:"choice",question:"Which Kafka component stores topics and their partitions?",options:["Broker","Producer","Consumer","Serializer"],answer:"Broker",explanation:"Kafka brokers store partition data and serve client requests."},
  {topic:"Kafka",level:"easy",type:"trueFalse",question:"Kafka messages can have keys and values.",answer:"True",explanation:"A Kafka record commonly contains a key, value, timestamp, and metadata."},
  {topic:"Kafka",level:"easy",type:"short",question:"What Kafka client publishes records to a topic?",answer:"producer",explanation:"A producer sends records to Kafka topics."},
  {topic:"Kafka",level:"medium",type:"choice",question:"What usually determines the partition for a keyed Kafka record?",options:["The record key","The consumer name","The broker port","The topic description"],answer:"The record key",explanation:"Kafka commonly hashes a record key to choose a partition."},
  {topic:"Kafka",level:"medium",type:"trueFalse",question:"Two consumers in the same consumer group normally share assigned partitions.",answer:"True",explanation:"Each partition is assigned to one consumer within a group at a time."},
  {topic:"Kafka",level:"medium",type:"short",question:"What Kafka operation confirms that a consumer processed a record position?",answer:"commit",explanation:"Consumers commit offsets to record their processing position."},
  {topic:"Kafka",level:"hard",type:"choice",question:"What happens when a Kafka consumer group member leaves?",options:["Partitions may be rebalanced","The topic is deleted","All offsets are erased","The broker shuts down"],answer:"Partitions may be rebalanced",explanation:"Kafka can rebalance partitions among remaining group members."},
  {topic:"Kafka",level:"hard",type:"trueFalse",question:"Kafka replication factor describes how many copies of partition data exist.",answer:"True",explanation:"Replication factor is the number of replicas for each partition."},
  {topic:"Git",level:"easy",type:"choice",question:"Which command displays the commit history?",options:["git log","git history","git commits","git timeline"],answer:"git log",explanation:"`git log` displays commits and their metadata."},
  {topic:"Git",level:"easy",type:"trueFalse",question:"`git add` places changes into the staging area.",answer:"True",explanation:"`git add` stages selected changes for the next commit."},
  {topic:"Git",level:"easy",type:"short",question:"Which command uploads local commits to a remote repository?",answer:"git push",explanation:"`git push` sends local commits and references to a remote."},
  {topic:"Git",level:"medium",type:"choice",question:"Which file tells Git which paths to ignore?",options:[".gitignore",".gitkeep",".gitconfig",".gitpaths"],answer:".gitignore",explanation:"`.gitignore` contains patterns for files Git should not track."},
  {topic:"Git",level:"medium",type:"trueFalse",question:"A merge conflict always means Git has corrupted the repository.",answer:"False",explanation:"A conflict means Git needs a person to choose between changes."},
  {topic:"Git",level:"medium",type:"short",question:"Which command creates and switches to a new branch in modern Git?",answer:"git switch -c",explanation:"`git switch -c branch-name` creates and checks out a new branch."},
  {topic:"Git",level:"hard",type:"choice",question:"What does `git cherry-pick` do?",options:["Applies a chosen commit onto the current branch","Deletes all branches","Compresses the repository","Renames the remote"],answer:"Applies a chosen commit onto the current branch",explanation:"Cherry-pick copies changes from selected commits onto the current branch."},
  {topic:"Git",level:"hard",type:"trueFalse",question:"A Git commit normally points to a tree representing the project files.",answer:"True",explanation:"A commit references a tree object containing the file snapshot."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are valid Java access modifiers?",options:["public","private","protected","friendly"],answer:["public","private","protected"],explanation:"Java provides public, protected, package-private, and private access levels.",optionExplanations:{public:"Accessible from any package.",private:"Accessible only within the declaring class.",protected:"Accessible in the package and in subclasses.",friendly:"Not a Java access-modifier keyword; package-private is the usual term."}},
  {topic:"Java",level:"hard",type:"choice",question:"Which are characteristics of an immutable Java object?",options:["Its state cannot change after construction","Fields are usually final","It exposes setters for all fields","It can safely share state between threads"],answer:["Its state cannot change after construction","Fields are usually final","It can safely share state between threads"],explanation:"Immutability means state does not change, which can simplify sharing between threads."},
  {topic:"SQL",level:"medium",type:"choice",question:"Which are SQL aggregate functions?",options:["COUNT","SUM","AVG","REPLACE"],answer:["COUNT","SUM","AVG"],explanation:"COUNT, SUM, and AVG summarize values across rows."},
  {topic:"SQL",level:"hard",type:"choice",question:"Which constraints help protect relational data integrity?",options:["PRIMARY KEY","FOREIGN KEY","UNIQUE","ORDER BY"],answer:["PRIMARY KEY","FOREIGN KEY","UNIQUE"],explanation:"These constraints enforce identity, relationships, and uniqueness."},
  {topic:"PostgreSQL",level:"medium",type:"choice",question:"Which are PostgreSQL transaction commands?",options:["BEGIN","COMMIT","ROLLBACK","SELECT ALL"],answer:["BEGIN","COMMIT","ROLLBACK"],explanation:"BEGIN starts a transaction; COMMIT saves it and ROLLBACK undoes it."},
  {topic:"PostgreSQL",level:"hard",type:"choice",question:"Which PostgreSQL features can improve query performance?",options:["Indexes","EXPLAIN analysis","Appropriate query predicates","Ignoring statistics"],answer:["Indexes","EXPLAIN analysis","Appropriate query predicates"],explanation:"Indexes, query-plan analysis, and selective predicates can improve performance."},
  {topic:"Spring Boot",level:"medium",type:"choice",question:"Which annotations commonly define Spring web endpoints?",options:["@GetMapping","@PostMapping","@RequestBody","@Autowired only"],answer:["@GetMapping","@PostMapping","@RequestBody"],explanation:"These annotations participate in request mapping and request-body binding."},
  {topic:"Spring Boot",level:"hard",type:"choice",question:"Which are common Spring bean scopes?",options:["singleton","prototype","request","compile-time"],answer:["singleton","prototype","request"],explanation:"Spring supports scopes such as singleton, prototype, request, and session."},
  {topic:"Kafka",level:"medium",type:"choice",question:"Which properties can affect Kafka delivery durability?",options:["acks","replication factor","min.insync.replicas","CSS selector"],answer:["acks","replication factor","min.insync.replicas"],explanation:"Acknowledgements and replica settings affect durability and delivery guarantees."},
  {topic:"Kafka",level:"hard",type:"choice",question:"Which are Kafka record delivery semantics?",options:["At most once","At least once","Exactly once","Never once"],answer:["At most once","At least once","Exactly once"],explanation:"Kafka systems can be designed around at-most-once, at-least-once, or exactly-once semantics."},
  {topic:"Git",level:"medium",type:"choice",question:"Which commands can integrate branch histories?",options:["git merge","git rebase","git cherry-pick","git status"],answer:["git merge","git rebase","git cherry-pick"],explanation:"These commands can bring commits or changes from another line of development."},
  {topic:"Git",level:"hard",type:"choice",question:"Which practices help keep Git history healthy?",options:["Small focused commits","Meaningful commit messages","Reviewing diffs before committing","Committing secrets"],answer:["Small focused commits","Meaningful commit messages","Reviewing diffs before committing"],explanation:"Focused commits, useful messages, and reviewing diffs improve collaboration and maintenance."},
  {topic:"Java",level:"easy",type:"choice",question:"Which keyword declares a Java package?",options:["package","namespace","module","group"],answer:"package",explanation:"The package declaration identifies the namespace of a Java source file."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"Java uses zero-based indexing for arrays.",answer:"True",explanation:"The first element of a Java array is at index zero."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword imports a class or package member?",answer:"import",explanation:"The import declaration makes types available by simple name."},
  {topic:"Java",level:"easy",type:"choice",question:"Which primitive type stores a whole number such as 42?",options:["int","boolean","char","double"],answer:"int",explanation:"int is the common 32-bit signed integer type."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"A Java String is an object rather than a primitive type.",answer:"True",explanation:"String is a final class in java.lang, not a primitive type."},
  {topic:"Java",level:"easy",type:"short",question:"Which method returns the number of characters in a String?",answer:"length",explanation:"String.length() returns the number of UTF-16 code units."},
  {topic:"Java",level:"easy",type:"choice",question:"Which symbol terminates most Java statements?",options:[";",":",".","#"],answer:";",explanation:"A semicolon terminates most declarations and expressions."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"Java comments can begin with two forward slashes.",answer:"True",explanation:"// starts a single-line comment in Java."},
  {topic:"Java",level:"easy",type:"short",question:"Which method prints text followed by a line break?",answer:"println",explanation:"System.out.println writes text and then a line separator."},
  {topic:"Java",level:"easy",type:"choice",question:"Which primitive type stores a single Unicode character?",options:["char","String","byte","boolean"],answer:"char",explanation:"char represents a UTF-16 code unit."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"The default value of an instance int field is zero.",answer:"True",explanation:"Numeric instance fields receive zero by default; local variables do not."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword exits a loop immediately?",answer:"break",explanation:"break transfers control out of the nearest loop or switch."},
  {topic:"Java",level:"easy",type:"choice",question:"Which keyword skips to the next loop iteration?",options:["continue","next","skip","pass"],answer:"continue",explanation:"continue skips the remaining body and proceeds with the next iteration."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"A Java array has a fixed length after creation.",answer:"True",explanation:"An array's length is fixed; use a collection for dynamic sizing."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword returns a value from a method?",answer:"return",explanation:"return ends a method and can provide its result."},
  {topic:"Java",level:"easy",type:"choice",question:"Which class is commonly used to read console input?",options:["Scanner","ConsoleReader","InputStreamReaderOnly","Keyboard"],answer:"Scanner",explanation:"java.util.Scanner can parse tokens from System.in."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"Java supports method overloading.",answer:"True",explanation:"Methods may share a name when their parameter lists differ."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword declares a method that belongs to the class rather than an instance?",answer:"static",explanation:"A static member belongs to the class itself."},
  {topic:"Java",level:"easy",type:"choice",question:"Which wrapper class corresponds to primitive int?",options:["Integer","NumberInt","IntObject","Long"],answer:"Integer",explanation:"Integer is the wrapper type for int values."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"The `==` operator compares primitive numeric values directly.",answer:"True",explanation:"For primitives, == compares values; for objects it compares references."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword defines a subclass relationship?",answer:"extends",explanation:"A class uses extends to inherit from another class."},
  {topic:"Java",level:"easy",type:"choice",question:"Which interface represents an ordered collection that may contain duplicates?",options:["List","Set","Map","Stream"],answer:"List",explanation:"List is ordered and can contain duplicate elements."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"A HashSet is designed to store duplicate elements.",answer:"False",explanation:"Set implementations generally enforce uniqueness."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword declares that a class implements an interface?",answer:"implements",explanation:"A class uses implements followed by one or more interfaces."},
  {topic:"Java",level:"easy",type:"choice",question:"Which collection stores key-value pairs?",options:["Map","List","Set","Queue"],answer:"Map",explanation:"Map associates keys with values."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"An enum can define a fixed set of named constants.",answer:"True",explanation:"Enums model a restricted set of predefined instances."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword prevents a class from being extended?",answer:"final",explanation:"A final class cannot have subclasses."},
  {topic:"Java",level:"easy",type:"choice",question:"Which access level is visible only inside the declaring class?",options:["private","public","protected","package"],answer:"private",explanation:"private members are accessible only within their declaring class."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"The main method conventionally returns void.",answer:"True",explanation:"The standard entry point has return type void."},
  {topic:"Java",level:"easy",type:"short",question:"Which primitive type represents true or false?",answer:"boolean",explanation:"boolean has the values true and false."},
  {topic:"Java",level:"easy",type:"choice",question:"Which class is immutable and commonly used for text?",options:["String","StringBuilder","StringBufferMutable","Text"],answer:"String",explanation:"String objects cannot be changed after creation."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"A constructor has the same name as its class.",answer:"True",explanation:"Constructors use the class name and have no return type."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword declares a constructor call to a parent class?",answer:"super",explanation:"super() invokes a parent constructor."},
  {topic:"Java",level:"easy",type:"choice",question:"Which operator performs logical AND with short-circuiting?",options:["&&","||","&","and"],answer:"&&",explanation:"&& evaluates the right side only when the left side is true."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"Java automatically manages memory using garbage collection.",answer:"True",explanation:"The JVM reclaims eligible heap objects automatically."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword creates a conditional branch alternative?",answer:"else",explanation:"else supplies the alternative branch of an if statement."},
  {topic:"Java",level:"easy",type:"choice",question:"Which loop is commonly used when the number of iterations is known?",options:["for","catch","switch","try"],answer:"for",explanation:"A for loop places initialization, condition, and update together."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"Local variables must be initialized before they are read.",answer:"True",explanation:"The compiler rejects reads of uninitialized local variables."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword handles an exception in a try statement?",answer:"catch",explanation:"catch receives an exception thrown by the associated try block."},
  {topic:"Java",level:"easy",type:"choice",question:"Which package contains ArrayList?",options:["java.util","java.io","java.net","java.sql"],answer:"java.util",explanation:"ArrayList is part of the java.util collections package."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"Java source code is normally compiled into bytecode.",answer:"True",explanation:"The compiler produces JVM bytecode, commonly in class files."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword declares a new interface?",answer:"interface",explanation:"The interface keyword declares an interface type."},
  {topic:"Java",level:"easy",type:"choice",question:"Which primitive type is commonly used for decimal values?",options:["double","boolean","char","shortText"],answer:"double",explanation:"double provides double-precision floating-point values."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"A do-while loop executes its body at least once.",answer:"True",explanation:"Its condition is checked after the body."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword starts an exception-handling block?",answer:"try",explanation:"try encloses code whose exceptions may be handled."},
  {topic:"Java",level:"easy",type:"choice",question:"Which class can build mutable strings efficiently?",options:["StringBuilder","StringLiteral","CharacterBuilder","TextArray"],answer:"StringBuilder",explanation:"StringBuilder supports mutable character sequences without creating a new String for each append."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"A Java class may implement more than one interface.",answer:"True",explanation:"Java supports multiple interface implementation."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword explicitly throws an exception?",answer:"throw",explanation:"throw transfers control by throwing one exception object."},
  {topic:"Java",level:"easy",type:"choice",question:"Which type is the parent of all Java reference types?",options:["Object","Root","Any","Reference"],answer:"Object",explanation:"Every class ultimately extends java.lang.Object directly or indirectly."},
  {topic:"Java",level:"easy",type:"trueFalse",question:"The Java compiler checks method argument types at compile time.",answer:"True",explanation:"Java is statically typed and checks method invocation compatibility."},
  {topic:"Java",level:"easy",type:"short",question:"Which keyword declares a method that cannot be overridden?",answer:"final",explanation:"A final method cannot be overridden by a subclass."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are valid inheritance relationships in Java?",options:["A class extends one class","A class implements many interfaces","An interface extends interfaces","A class extends many classes"],answer:["A class extends one class","A class implements many interfaces","An interface extends interfaces"],explanation:"Java has single class inheritance and supports multiple interface inheritance."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Overriding requires a compatible method signature in a subclass.",answer:"True",explanation:"An overriding method must follow Java's override rules."},
  {topic:"Java",level:"medium",type:"short",question:"Which annotation verifies that a method overrides a parent method?",answer:"@Override",explanation:"@Override lets the compiler detect an incorrect override."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are unchecked exceptions?",options:["NullPointerException","IllegalArgumentException","IOException","ArithmeticException"],answer:["NullPointerException","IllegalArgumentException","ArithmeticException"],explanation:"RuntimeException subclasses are unchecked; IOException is checked."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"A checked exception extends RuntimeException.",answer:"False",explanation:"Checked exceptions generally extend Exception without RuntimeException."},
  {topic:"Java",level:"medium",type:"short",question:"Which keyword declares exceptions a method may pass to its caller?",answer:"throws",explanation:"throws appears in a method signature to declare propagated exceptions."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are functional interfaces?",options:["Runnable","Predicate","Comparator","ArrayList"],answer:["Runnable","Predicate","Comparator"],explanation:"These interfaces can be represented by lambdas; ArrayList is a collection."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"A lambda can target an interface with exactly one abstract method.",answer:"True",explanation:"Such an interface is a functional interface."},
  {topic:"Java",level:"medium",type:"short",question:"Which interface accepts one argument and returns a result?",answer:"Function",explanation:"Function<T,R> maps a T input to an R result."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are intermediate Stream operations?",options:["filter","map","sorted","collect"],answer:["filter","map","sorted"],explanation:"collect is terminal; the others are intermediate operations."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Java Streams are usually lazy until a terminal operation runs.",answer:"True",explanation:"Intermediate operations generally execute only when needed."},
  {topic:"Java",level:"medium",type:"short",question:"Which Stream operation gathers elements with a Collector?",answer:"collect",explanation:"collect performs a mutable reduction."},
  {topic:"Java",level:"medium",type:"choice",question:"Which collections provide ordering behavior?",options:["TreeSet","LinkedHashMap","HashSet","PriorityQueue"],answer:["TreeSet","LinkedHashMap","PriorityQueue"],explanation:"TreeSet sorts, LinkedHashMap preserves insertion order, and PriorityQueue orders by priority."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"HashMap permits one null key.",answer:"True",explanation:"HashMap permits one null key and multiple null values."},
  {topic:"Java",level:"medium",type:"short",question:"Which map preserves insertion order?",answer:"LinkedHashMap",explanation:"LinkedHashMap maintains insertion order by default."},
  {topic:"Java",level:"medium",type:"choice",question:"Which methods compare String content?",options:["equals","equalsIgnoreCase","compareTo","== for content"],answer:["equals","equalsIgnoreCase","compareTo"],explanation:"String methods compare content; == compares references."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"String concatenation can create new String objects.",answer:"True",explanation:"Strings are immutable, so concatenation may create new objects."},
  {topic:"Java",level:"medium",type:"short",question:"Which method compares strings without considering case?",answer:"equalsIgnoreCase",explanation:"equalsIgnoreCase compares content independent of case."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are Java primitive numeric types?",options:["byte","short","int","Integer"],answer:["byte","short","int"],explanation:"Integer is a wrapper class, not a primitive."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Widening a smaller integer primitive is usually implicit.",answer:"True",explanation:"An int can be assigned to a long without an explicit cast."},
  {topic:"Java",level:"medium",type:"short",question:"Which syntax performs a narrowing cast to int?",answer:"(int)",explanation:"A narrowing conversion can use an explicit (int) cast."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are object-oriented principles?",options:["Encapsulation","Inheritance","Polymorphism","Compilation only"],answer:["Encapsulation","Inheritance","Polymorphism"],explanation:"These are core object-oriented ideas; compilation is a language process."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Polymorphism can use a parent reference for a child implementation.",answer:"True",explanation:"Dynamic dispatch selects overridden child behavior."},
  {topic:"Java",level:"medium",type:"short",question:"What hides implementation details behind a public API?",answer:"encapsulation",explanation:"Encapsulation controls access to internal state and behavior."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are constructor facts?",options:["They have no return type","They can be overloaded","They can call another constructor","They are inherited"],answer:["They have no return type","They can be overloaded","They can call another constructor"],explanation:"Constructors have no return type, may be overloaded, and can delegate."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Constructors are inherited by subclasses.",answer:"False",explanation:"Constructors are not inherited, though subclasses can call them."},
  {topic:"Java",level:"medium",type:"short",question:"Which keyword calls another constructor in the same class?",answer:"this",explanation:"this(...) delegates to another constructor in the same class."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are nested Java type forms?",options:["Static nested class","Inner class","Local class","SQL class"],answer:["Static nested class","Inner class","Local class"],explanation:"Java supports static nested, inner, local, and anonymous classes."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"An inner class can access its enclosing instance's members.",answer:"True",explanation:"A non-static inner class has an enclosing instance."},
  {topic:"Java",level:"medium",type:"short",question:"Which nested class has no implicit enclosing instance?",answer:"static nested class",explanation:"A static nested class belongs to the outer class, not an outer object."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are concurrency tools in java.util.concurrent?",options:["ExecutorService","CountDownLatch","ConcurrentHashMap","StringTokenizerOnly"],answer:["ExecutorService","CountDownLatch","ConcurrentHashMap"],explanation:"These support task execution, coordination, and concurrent maps."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Calling start on a Thread creates a new execution path.",answer:"True",explanation:"start schedules a thread; calling run directly does not."},
  {topic:"Java",level:"medium",type:"short",question:"Which keyword protects a critical section with an intrinsic monitor?",answer:"synchronized",explanation:"synchronized provides mutual exclusion and visibility."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are benefits of immutable objects?",options:["Thread safety benefits","Safe cache keys","No setter mutation","They require public fields"],answer:["Thread safety benefits","Safe cache keys","No setter mutation"],explanation:"Immutable state is easier to share and stable as a map key."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Changing a field used by hashCode can make a HashMap key hard to find.",answer:"True",explanation:"Hash-based lookup depends on a key remaining stable."},
  {topic:"Java",level:"medium",type:"short",question:"Which interface defines natural ordering?",answer:"Comparable",explanation:"Comparable defines compareTo for natural ordering."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are standard Java date-time types?",options:["LocalDate","Instant","Duration","DateOnlyText"],answer:["LocalDate","Instant","Duration"],explanation:"java.time provides types for dates, instants, and elapsed time."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"LocalDate stores a time zone.",answer:"False",explanation:"LocalDate stores a date without time or zone information."},
  {topic:"Java",level:"medium",type:"short",question:"Which type represents a moment on the UTC timeline?",answer:"Instant",explanation:"Instant represents a point on the timeline."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are common Object methods?",options:["toString","equals","hashCode","calculateSql"],answer:["toString","equals","hashCode"],explanation:"Object defines methods for representation and equality."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Every Java class has Object as an ancestor directly or indirectly.",answer:"True",explanation:"Classes without another superclass implicitly extend Object."},
  {topic:"Java",level:"medium",type:"short",question:"Which Object method returns a text representation?",answer:"toString",explanation:"toString provides an object's string representation."},
  {topic:"Java",level:"medium",type:"choice",question:"Which are useful enum properties?",options:["Type safety","Fixed instances","Methods","Only arbitrary strings"],answer:["Type safety","Fixed instances","Methods"],explanation:"Enums define type-safe constants and may contain methods."},
  {topic:"Java",level:"medium",type:"trueFalse",question:"Enum constants can have constructor arguments.",answer:"True",explanation:"Enum constants may pass arguments to the enum constructor."},
  {topic:"Java",level:"medium",type:"short",question:"Which method returns all constants of an enum?",answer:"values",explanation:"The compiler provides values() for every enum type."},
  {topic:"Java",level:"hard",type:"choice",question:"Which are properties of Java generics?",options:["They provide compile-time type checks","They reduce casts","They support bounded type parameters","They make primitives generic directly"],answer:["They provide compile-time type checks","They reduce casts","They support bounded type parameters"],explanation:"Generics improve type safety and support bounds; primitive type arguments use wrappers."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"Type erasure means most generic type arguments are not retained as runtime generic types.",answer:"True",explanation:"Java commonly implements generics through type erasure."},
  {topic:"Java",level:"hard",type:"short",question:"Which keyword restricts a generic type parameter to a bound?",answer:"extends",explanation:"T extends SomeType declares an upper bound."},
  {topic:"Java",level:"hard",type:"choice",question:"Which are valid wildcard concepts?",options:["? extends Number","? super Integer","Unbounded ?","? implements Runnable"],answer:["? extends Number","? super Integer","Unbounded ?"],explanation:"Wildcards use extends or super; implements is not wildcard bound syntax."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"A List<? extends Number> can safely add an arbitrary Integer.",answer:"False",explanation:"The exact subtype is unknown, so adding values is generally unsafe."},
  {topic:"Java",level:"hard",type:"short",question:"Which generic concept describes accepting a consumer of a type or its supertypes?",answer:"super wildcard",explanation:"A ? super T wildcard is useful when a structure consumes T values."},
  {topic:"Java",level:"hard",type:"choice",question:"Which can cause a Java memory leak in a long-running application?",options:["Unbounded static collection","Listener never removed","ThreadLocal never cleared","A local variable that goes out of scope"],answer:["Unbounded static collection","Listener never removed","ThreadLocal never cleared"],explanation:"Long-lived references prevent otherwise unused objects from being collected."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"Garbage collection guarantees that every unused object is reclaimed immediately.",answer:"False",explanation:"Collection timing is managed by the JVM and is not an immediate guarantee."},
  {topic:"Java",level:"hard",type:"short",question:"What JVM memory area stores objects created with new?",answer:"heap",explanation:"Objects are allocated in the JVM heap, subject to implementation details."},
  {topic:"Java",level:"hard",type:"choice",question:"Which are happens-before relationships in the Java Memory Model?",options:["Unlock before a later lock on the same monitor","A volatile write before a later volatile read","Thread start before actions in the started thread","Any ordinary write before any read"],answer:["Unlock before a later lock on the same monitor","A volatile write before a later volatile read","Thread start before actions in the started thread"],explanation:"These specified relationships provide visibility and ordering; ordinary accesses alone do not."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"volatile guarantees visibility but does not make every compound operation atomic.",answer:"True",explanation:"volatile prevents stale reads but does not make read-modify-write sequences atomic."},
  {topic:"Java",level:"hard",type:"short",question:"Which class provides an atomic integer counter?",answer:"AtomicInteger",explanation:"AtomicInteger provides atomic operations for an int value."},
  {topic:"Java",level:"hard",type:"choice",question:"Which are common causes of deadlock?",options:["Circular lock waiting","Inconsistent lock ordering","Holding a lock while waiting for another","Using an immutable local value"],answer:["Circular lock waiting","Inconsistent lock ordering","Holding a lock while waiting for another"],explanation:"Deadlocks require threads to wait in a cycle for resources held by one another."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"Acquiring multiple locks in one consistent global order can reduce deadlock risk.",answer:"True",explanation:"Consistent ordering prevents many circular wait conditions."},
  {topic:"Java",level:"hard",type:"short",question:"What is the condition where threads wait forever for one another's locks called?",answer:"deadlock",explanation:"Deadlock is a circular wait in which no thread can progress."},
  {topic:"Java",level:"hard",type:"choice",question:"Which are checked exception handling strategies?",options:["Catch the exception","Declare it with throws","Ignore it silently","Wrap it in an appropriate exception"],answer:["Catch the exception","Declare it with throws","Wrap it in an appropriate exception"],explanation:"Checked exceptions must be handled or declared; wrapping can preserve context."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"A try-with-resources statement closes AutoCloseable resources automatically.",answer:"True",explanation:"Resources are closed at the end of the try-with-resources statement."},
  {topic:"Java",level:"hard",type:"short",question:"Which interface must a try-with-resources object implement?",answer:"AutoCloseable",explanation:"AutoCloseable defines close() for automatic resource cleanup."},
  {topic:"Java",level:"hard",type:"choice",question:"Which are features of records?",options:["Compact data carriers","Generated accessors","Generated equals and hashCode","They are always mutable"],answer:["Compact data carriers","Generated accessors","Generated equals and hashCode"],explanation:"Records reduce boilerplate for shallowly immutable data carriers."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"A record's component reference cannot be reassigned after construction.",answer:"True",explanation:"Record components are final fields, though referenced objects may still be mutable."},
  {topic:"Java",level:"hard",type:"short",question:"Which Java feature provides concise pattern matching over data shapes?",answer:"pattern matching",explanation:"Modern Java pattern matching can combine type tests with variable binding."},
  {topic:"Java",level:"hard",type:"choice",question:"Which are module-system concepts?",options:["exports","requires","opens","package-private keyword module"],answer:["exports","requires","opens"],explanation:"Java modules declare dependencies, exports, and reflective openings in module-info.java."},
  {topic:"Java",level:"hard",type:"trueFalse",question:"The Java module path and class path are identical concepts.",answer:"False",explanation:"The module path resolves named modules, while the class path resolves traditional class-path entries."},
  {topic:"Java",level:"hard",type:"short",question:"Which file declares a named Java module?",answer:"module-info.java",explanation:"module-info.java contains a module declaration and its directives."}
];
